### PR TITLE
fix: add hydration to initial value hook

### PR DESCRIPTION
**Pull request by jaredLunde**
- Adds Jotai hydration to the initial value hook which has potential side effects for existing forms
- Better handle form resetting

### CODE REVIEW

**Comment by schiller-manuel** [comment]
can you revert to the equality checking introduced in https://github.com/form-atoms/form-atoms/commit/c7d2751d53da2eb3be616eb32f4b71a66592ab5a?
It causes this issue for me: https://github.com/form-atoms/field/issues/104

Why can't we rely on React's dependency tracking?

**Comment by jaredLunde** [comment]
Using React dependency tracking doesn't work for objects/arrays

**Comment by schiller-manuel** [comment]
yeah the user needs to care about referential equality, but this is typical in React libraries.

**Comment by jaredLunde** [comment]
If I reverted, you have a bug and you aren't aware of it. With the way things are now, you have a bug and you know it :)

**Comment by MiroslavPetrik** [comment]
> If I reverted, you have a bug and you aren't aware of it. With the way things are now, you have a bug and you know it :)

I think I'm with @schiller-manuel on this one. E.g. the `areEqual` is basically second check for `dirty` (when field.value is compared).
I tried to wrap my head around implementation for the listField, but all ended up looking like trash

**Comment by jaredLunde** [comment]
Not sure what the suggestion is. What good does reverting do?

**Comment by MiroslavPetrik** [comment]
@jaredLunde we just want to return to the original version, where the efeect hook uses depeneencies as it should...

No need for anything special for the listField here.

Whats the point of the areEqual? I believe it was added to fix the issue of set-in-render we had earlier and now is not needed as you merged the hydration which we originally wanted.

So like we need one step back on that front 😁

**Comment by jaredLunde** [comment]
I'm not reverting the change. Outside of potential bug fixes this library is "done" at this point as the project goals have been achieved. `areEqual` solves an initial value case for something like below where you have a `<textarea>` that has email addresses separated by commas.

```ts
// Atoms
const sendInvitesFormStore = createStore();
const sendInvitesForm = formAtom({
  emails: fieldAtom<string[]>({
    value: [],
    validate: validate(
      z.array(z.string().email()).nonempty(
        "Must contain at least one email address.",
      ).max(25, "Must contain at most 25 email addresses"),
    ),
  }),
});
```

```tsx
// Field
<Form.Field
  atom={fields.emails}
  initialValue={["some@initial.value"]}
  render={(state, actions) => {
    return (
      <Input.DescriptiveLabel
        title="Email addresses"
        description={
          <>
            Send up to 25 invites at a time. Separate multiple email addresses
            with commas.
          </>
        }
      >
        <Textarea
          autoResize
          autoFocus
          placeholder="ella@flexstack.co, kamal@flexstack.co..."
          rows={4}
          value={state.value.join(", ")}
          onChange={(event) => {
            actions.setValue(
              event.currentTarget.value
                .split(/,\s+/g)
                .map((v) => v.trim()),
            );
          }}
        />
      </Input.DescriptiveLabel>
    );
  }}
/>
```

Again, this is an issue with your field, not the library. The library works as advertised.

**Pull request merged**
