### PR TITLE
fix: add reusable useHydrateField

### PR DESCRIPTION
**Pull request by MiroslavPetrik**
This enables custom hydration and possibly rehydration via an underlying options flag.

### CODE REVIEW

**Comment by jaredLunde** [comment]
I don't believe this belongs in the standard library

**Comment by MiroslavPetrik** [comment]
The hook encapsulates the implementation detail, that the fieldAtom has 2 atoms namely `value` and `_initialAtom`.
So that way, the hook is a glue between the jotai hook & the internals of fieldAtom.

Given that its already used in the `useFIV` hook, or put differently I've only extracted it, it makes sense to me that its the part of the core.

It does not extend any functionality, beyond the fact that the options flag is now not hidden. hmmm

**Comment by jaredLunde** [comment]
It absolutely, positively does not necessitate its own abstraction in any way, shape, or form. I will not budge.

https://github.com/form-atoms/form-atoms/issues/68#issuecomment-1937821799

**Comment by MiroslavPetrik** [comment]
Interesting I would not call this abstraction at all. I think I've only refactored the code - extracted a reusable procedure.

I think of the `useHydrateAtoms` from jotai as a generic util which can work for aaaany custom thing you need.
But then as you have a `fieldAtom`, when you apply its shape into the generic util, you get a concrete one `useHydrateField` which specifically says, that ok, we are hydrating with the jotai util, but this one we need this exact structure.

Maybe we are of different schools :D

**Pull request closed without merging**
